In [ ]:
## Pca 

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [10]:
from sklearn.datasets import load_iris
data = load_iris()

In [6]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [14]:
x = data.data
y = data.target

In [15]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
# train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=1)

In [20]:
from sklearn.preprocessing import StandardScaler # mean = 0, sigma = 1
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [21]:
from sklearn.decomposition import PCA
pca = PCA()
pca

PCA()

In [23]:
x_train = pca.fit_transform(x_train)
x_train

array([[ 3.29187211e+00, -1.64765395e-01,  7.27509357e-01,
        -5.78968617e-02],
       [-1.79681257e+00,  1.59337640e+00,  4.43385293e-01,
        -8.32121597e-02],
       [-2.30351105e+00,  8.69431210e-01,  2.33792304e-02,
         2.34275331e-02],
       [-2.02984587e+00, -5.59980278e-01,  3.92793836e-02,
        -1.38513261e-01],
       [ 9.09507841e-03, -9.68249823e-01, -5.55780350e-01,
         3.73471773e-02],
       [-2.09778967e+00,  4.52095658e-01,  1.94589630e-01,
        -1.74901668e-02],
       [-1.96393609e+00,  8.23951366e-01,  5.15626453e-01,
        -2.10836333e-01],
       [ 2.49741981e+00,  2.55439705e+00,  2.78249238e-01,
         2.39201187e-01],
       [ 1.87223188e+00,  6.45015818e-01,  7.34520648e-02,
        -2.04303483e-01],
       [ 2.31306020e+00,  3.19175762e-01,  6.91328103e-01,
         2.17802182e-01],
       [ 1.85690136e+00, -2.09457613e-01, -3.25721459e-01,
        -9.87875317e-02],
       [ 1.17626383e+00, -3.27992385e-01, -1.15904903e-01,
      

In [24]:
x_test = scaler.transform(x_test)
x_test = pca.transform(x_test)
x_test

array([[-1.02338658e-15,  2.30740390e+00, -1.42579845e+00,
        -1.27095115e+00],
       [-8.32816412e-01, -1.29077545e+00, -4.14631819e-01,
        -1.16096500e-01],
       [ 9.51790185e-01, -9.13823325e-02,  3.71831115e-01,
         2.68855052e-01],
       [-4.75895093e-01,  2.06752527e+00, -1.36962252e+00,
        -1.01431679e+00],
       [ 2.49844924e+00,  1.82764665e+00,  1.49534959e+00,
         1.03875815e+00],
       [ 5.94868866e-01,  6.28253536e-01,  5.40358887e-01,
         5.25489419e-01],
       [ 1.30871150e+00,  1.48496290e-01,  7.65062582e-01,
         1.42370971e+00],
       [-8.32816412e-01,  1.82764665e+00, -1.03256698e+00,
        -1.01431679e+00],
       [-1.30871150e+00,  3.88374913e-01, -1.20109475e+00,
        -1.27095115e+00],
       [ 1.30871150e+00,  3.88374913e-01,  1.10211813e+00,
         1.42370971e+00],
       [-2.37947546e-01, -8.11018201e-01,  2.59479267e-01,
         1.40537868e-01],
       [-4.75895093e-01,  2.06752527e+00, -1.14491883e+00,
      

In [25]:
pca.components_

array([[ 1.00000000e+00,  5.78241551e-17, -8.71166547e-17,
         1.16599365e-16],
       [-5.78241551e-17,  1.00000000e+00, -0.00000000e+00,
         1.11022302e-16],
       [ 8.71166547e-17, -0.00000000e+00,  1.00000000e+00,
        -2.49800181e-15],
       [-1.16599365e-16, -2.22044605e-16,  2.44249065e-15,
         1.00000000e+00]])

In [28]:
x_train.shape

(105, 4)

In [29]:
# train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=1)

from sklearn.preprocessing import StandardScaler # mean = 0, sigma = 1
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

pca = PCA(n_components=3)
x_train = pca.fit_transform(x_train)
x_train

array([[ 3.29187211, -0.16476539,  0.72750936],
       [-1.79681257,  1.5933764 ,  0.44338529],
       [-2.30351105,  0.86943121,  0.02337923],
       [-2.02984587, -0.55998028,  0.03927938],
       [ 0.00909508, -0.96824982, -0.55578035],
       [-2.09778967,  0.45209566,  0.19458963],
       [-1.96393609,  0.82395137,  0.51562645],
       [ 2.49741981,  2.55439705,  0.27824924],
       [ 1.87223188,  0.64501582,  0.07345206],
       [ 2.3130602 ,  0.31917576,  0.6913281 ],
       [ 1.85690136, -0.20945761, -0.32572146],
       [ 1.17626383, -0.32799238, -0.1159049 ],
       [ 0.47719569,  0.94245595, -0.37922585],
       [ 2.89869104,  0.26080541,  0.89541384],
       [ 0.11585216, -0.11732141, -0.11322366],
       [-2.25559918,  0.3433037 , -0.07650505],
       [ 1.23365863, -1.17336962, -0.59631281],
       [ 1.32731302, -0.51778801,  0.00983591],
       [-2.1752965 , -0.57817266,  0.20174816],
       [-2.30829256, -0.15174092, -0.05069663],
       [ 1.87676437,  0.28447677, -0.343

In [30]:
pca.n_components

3

In [31]:
pca.explained_variance_ratio_

array([0.7215793 , 0.23455023, 0.03959537])